### ISSUE TITLE
Create Super Admin and limit power of admins

### ISSUE THREAD

**Issue by gscardine** [LordAlexWorks/tamarin#15]
Account == GIW
GIW can have X Users
A setting by Account
Only the user who is admin can edit Accoun't settings
- [ ] Admin should only see their own members
- [ ] Super admins should see all admins, and all members
- [ ] Settings should be per admin

**Comment by bolom** [comment]
```
Organisations

- id
- name
- settings **jsonb**
```

```
Users
id
email
password
organisation_id
```

```
Members
id
email
...
organisation_id

```

**Comment by bolom** [comment]
@gscardine for the moment we will do something easier

no super admin or admin just add an layer organisation
