### ISSUE TITLE
Export members with membership date filter 

### ISSUE THREAD

**Issue by gscardine** [LordAlexWorks/tamarin#23]
- [x] have the list of the month (and/or for the last 2 weeks) of the new members and the possibility to export their registered datas into a csv ? (best way to import them in the internal social network)
- [x] have the expired (ie the one whose email address has been erased - expiration +30 days then) of the month on a list that can be exported (same datas as the registered) in order to remove them from the internal social network
### Idea
- Display a form to select date range
- Present dates as suggestion:
  - "New members" = added 30- days ago  (number of days from settings)
  - "Expired members" = membership expired 30+ days ago (number of days from settings)

**Comment by bolom** [comment]
did you already add the improvements?
- Display a form to select date range
- Present dates as suggestion:

**Comment by gscardine** [comment]
Ops, missed this question.
Yes I have, they're both done here: https://github.com/LordAlexWorks/tamarin/pull/26
