### ISSUE TITLE
Dashboard with information and statistics

### ISSUE THREAD

**Issue by gscardine** [LordAlexWorks/tamarin#24]
## Numbers
- [x] total numbers of registered members
  - [x] number
  - [x] statistics
  
  &nbsp;
- [x] re-registration rate (compared to last month and to last year)
  - [x] number
  - [x] statistics
  
  &nbsp;
## Others
- [x] average age
- [x] most common job
  
  &nbsp;
## List and numbers
- [x] new members this month (compared to last month and last year)
  - [x] list
  - [x] number
  - [x] statistics
  
  &nbsp;
- [x] soon to be expire members this month (1st call, 2nd call, 3rd call compared to last month and last year) : list and numbers
  - [x] list
  - [x] number
  - [x] statistics
  
  &nbsp;
- [x] new expired this month (compared to last month and last year) : list and numbers
  - [x] list
  - [x] number
  - [x] statistics
  
  &nbsp;
## Links
- [x] export **new** members
- [x] export **soon to be deactivated** members
- [x] export **recently deactivated** members

**Comment by bolom** [comment]
@gscardine could you checked the issues already done?

**Comment by bolom** [comment]
@gscardine when the issue is done let me know
