### ISSUE TITLE
parse csv file in the database

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/tamarin#3]

**Comment by gscardine** [comment]
Hi Bolo,

I started parsing the CSV file, but I have some doubts.
1. Will they continue working with CSV even after the system is in place?
2. The file is not very well formed. Can they regenerate the files or is that out of question? If they can, this is what I need of the files:
   - Enclose all strings with " (for example: "this is a string";"this is another")
   - Having each line break represent a different entry (right now some lines break in the middle)

If it's hard to regenerate the files or if they're many, it's ok, tomorrow I'll look more into how to identify the columns :-)

Thanks!

**Comment by bolom** [comment]
1. Will they continue working with CSV even after the system is in place?

Yes maybe couple times until the application is done
1. The file is not very well formed. Can they regenerate the files or is that out of question? If they can, this is what I need of the files:

She can . I don't think it will change anything. Could you ask Marie-Amelie for that ?
